apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: menu-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: menu
  targetCPUUtilizationPercentage: 60