apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: menu
  name: menu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - image: menu-service
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                name: menu-config
        name: menu
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 20112
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 20112
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 20112
          failureThreshold: 30
          periodSeconds: 10