apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: book-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: book
  targetCPUUtilizationPercentage: 60
