apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: book
  name: book
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - image: book-service
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                name: book-config
        name: book
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 20111
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 20111
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 20111
          failureThreshold: 30
          periodSeconds: 10