kind: PersistentVolume
apiVersion: v1
metadata:
  name: game-service-db2-pv-volume
  labels:
    type: local
    app: game-service-db2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Data/GameServiceDB2
    type: DirectoryOrCreate