apiVersion: v1
kind: Service
metadata:
  name: game-service-db2-service
  labels:
    app: game-service-db2
spec:
  type: NodePort
  ports:
    - port: 20207
      targetPort: 5432
      nodePort: 30208
  type: NodePort
  selector:
    app: game-service-db2