apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-db2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  game-service-db2
  template:
    metadata:
      labels:
        app:  game-service-db2
    spec:
      containers:
        - name: postgres
          image: postgres:10.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: game-service-db2-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - name: max-conns
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: game-service-db2-pv-claim
        - name: max-conns
          configMap:
            name: user-service-db2-config-maxcons