apiVersion: v1
kind: ConfigMap
metadata:
  name: game-service-db2-config
  labels:
    app: game-service-db2
data:
  POSTGRES_USER: Server
  POSTGRES_PASSWORD: ServerPassWitcher

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-db2-config-maxcons
  labels:
    app: user-service-db2
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 500;"